---
- name: Install unattended-upgrades package and update-notifier-common
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - unattended-upgrades
    - update-notifier-common
  tags:
    - apt
    - unattended-upgrades

- name: Configure unattended-upgrades to update the packages from sources.list.
  copy:
    src: 20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: 0644
    owner: root
    group: root
  tags:
    - apt
    - unattended-upgrades

- name: Configure unattended-upgrades to update the packages from sources.list.
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: 0644
    owner: root
    group: root
  tags:
    - apt
    - unattended-upgrades

- name: Add cron job to indicate to unattended-upgrades that a reboot is required.
  cron:
    name: Indicate that a reboot is required at the scheduled time.
    job: "touch /var/run/reboot-required"
    hour: "*/12"
  tags:
    - cron
    - unatted-upgrades
